### ISSUE TITLE
Autocomplete failing

### ISSUE THREAD

**Issue by jdlovins** [Timocop/BasicPawn#1]
Hey i setup BasicPawn and the autocomplete does not seem to work at all for some reason. It fails at
http://i.imgur.com/F9LWhK7.png

**Comment by Timocop** [comment]
Can you show the "Information" tab?
You need to save your source on disk first. And if your source is not in the "scripting" folder next to the compiler and includes you may need to set the include, output and compiler path manually in the configs.

![](https://cloud.githubusercontent.com/assets/22834512/23634388/43bcbf08-02ca-11e7-86e1-40ec83ffdb5b.gif)

**Comment by jdlovins** [comment]
Ah i see. Thats what i was getting, i thought the autocomplete worked like a usual IDE does where its near your mouse cursor. I guess nothing is actually wrong

Something that would really help is allowing multiple include directories. It would make your program a lot better to use

**Comment by Timocop** [comment]
You can enable the on-screen tooltip in the settings. The on-screen toolip is not final and will be changed in later commits.
And im going to add the multi-include functionality. Thanks for the Feedback!

![](https://cloud.githubusercontent.com/assets/22834512/23665252/41d83418-0358-11e7-9bd9-432641a18a38.gif)
