### ISSUE TITLE
[Feature Request] Current scope highlighting - limit minimum lines count

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#101]
Hi,

Personally, by default, this option is annoying me when it every time highlights scopes that have the minimal size (but I don't want to disable it completely).

It especially useful for code parts where scope is too long.

Could you, please, add a text field option next to "Current Scope Highlithing" option, that would allow specifying the minimum lines count of the scope, which this highlighting should affect only?

Thanks in advance, and good day to you!

**Comment by Timocop** [comment]
Done. e602e8127272c5d7ef06e5ba26c836a0eda24e66
