### ISSUE TITLE
[Feature Request] Hotkey: Ctrl + F4 to close current tab

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#103]
It would be useful for fast managing, to have a hotkey like in other text editors - Ctrl + F4 for closing the current tab.

Kind regards,
Stanislav.

**Comment by DosMike** [comment]
The default for "close active" is `CTRL+W` ([a lot of applications use this shortcut that way](https://defkey.com/what-means/ctrl-w)).
Works in BasicPawn for me as well.

**Comment by dragokas** [comment]
Well, that sucks the different applications use different (alternate) "default" hotkeys.
Thanks for letting me know.

**Comment by dragokas** [comment]
I'd really love to be able to manually change hotkeys to any desired one.

**Comment by Timocop** [comment]
Hotkey changes is planed in the future. I assume this can be closed since there is already a hotkey for it?

**Comment by dragokas** [comment]
Yeah, thanks for that )
