### ISSUE TITLE
Improve parsing of global variables within #include (for AutoComplete)

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#106]
With
```
Profiler g_hProf;
```
Usually when you type "g_hProf." IntelliSense and AutoComplete is automatically giving you a tip.

But, when
```
Profiler g_hProf;
```
is located within include, like: in localizer.inc

Then, you connect it with:

```
#include <localizer>
```
but IntelliSense does not react to typing "g_hProf." anymore.

**Comment by Timocop** [comment]
Enable it in the settings:
![2021-06-19_13-30-37](https://user-images.githubusercontent.com/22834512/122640962-8e271d80-d102-11eb-89f9-6f4c1b8de9f4.png)

**Comment by dragokas** [comment]
oww, thanks )

**Comment by dragokas** [comment]
EDIT. I had that already enabled.

**Comment by Timocop** [comment]
And it still does not work? Should work just fine, i don't see a reason why it doesn't. 
Make sure you save the changes otherwise it does not work.
Is it referenced when you open both Source and Include file?

**Comment by dragokas** [comment]
I even tried to open "sourcemod.inc" via Object explorer and add somewhere at the end:

```
ArrayList al;
```
Then save, reload project, but in OnPluginStart typing "al." show no tips.

I have such options:
![image](https://user-images.githubusercontent.com/19956568/122649327-00fdbc00-d136-11eb-9bd3-baee52cd882a.png)

**Comment by dragokas** [comment]
ahh, sorry, I'm sleeping.

I was need 3rd option "Parse from all includes".

Again, sorry.
