### ISSUE TITLE
[Feature Request] Automatically open include files together with sp

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#107]
Hi,
It's very often happening to me to open various sp files with its includes.

Can I ask to add the possibility for auto-open all #include files (sp & inc) as soon as you open main (any) sp file (including those located in the relative subfolder)?

Like, an additional option next to:
![image](https://user-images.githubusercontent.com/19956568/122676107-1f6ec080-d1e5-11eb-9fd4-09838e9ecf1b.png)

Sorry, for asking so many features.

**Comment by Timocop** [comment]
The project browser will change in the next update. A lot of things will be different and removed (such as absolute paths and packing).
And no need to be sorry for asking for features, all good 😃

**Comment by dragokas** [comment]
OMG, I opened same issue twice O_o.
https://github.com/Timocop/BasicPawn/issues/100

> The project browser will change in the next update. A lot of things will be different and removed (such as absolute paths and packing).
Wow, will be waiting )
