### ISSUE TITLE
#region imitation for code folding

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#110]
There is no #region directive in SourceMod.

But, the ability to implement somehow its imitation by IDE for purposes of folding a set of functions would be really great.

I really don't have good options as example in mind, maybe, allow IDE to detect something like:
```
// #region MyRegion

void foo1()
{
}
void foo2()
{
}

// #endregion
```

Respectively, ability to save folding states in per-project settings file.

**Comment by Timocop** [comment]
You can already do that by using comments and backets. Without #region.
```cpp
// {

void foo1()
{
}
void foo2()
{
}

// }
```
