### ISSUE TITLE
Per file configurations.

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#12]
Hi,

Is it possible to have per file configurations? I mean I file file "x"  that should have always this configuration "x", the file "y" of another project should be have always its configurations and so on.
So every time that I change project I dont have always to change the settings.

**Comment by Timocop** [comment]
Yes it is possible. I might change the way configs work. Instead of using global configs, it will be per-tab instead as you said. However, instead of changing the config all the time, it will remember the config and set it when opening a file if you already set the config previously.

**Comment by Timocop** [comment]
Done. You can now set configs by file/tabs.
