### ISSUE TITLE
"Unable to search nothing" error

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#121]
Hi,

there is amazing built-in feature "Convert Tabs & Spaces" which is fine.

However, when I try to do it manually via Ctrl + F, type in search fileld 4 spaces -> Press "Search", editor tells me that it is "Unable to search nothing".

**Comment by Timocop** [comment]
Will fix this. For a workaround use regular expressions filter `\s\s\s\s` which has the same effect as 4 spaces.

**Comment by Timocop** [comment]
Fixed in 6cb2916ee042777132d33108532671414460dc36
