### ISSUE TITLE
Add the "Trim Trailing Space" tool / macro from notepad++

### ISSUE THREAD

**Issue by Nickelony** [Timocop/BasicPawn#13]
It would be nice to add this tool since it's very useful to keep the code clean.
Adding an option to do all the code cleaning (Formating and Trim Trailing) after saving would be also nice. :)

**Comment by Timocop** [comment]
Done.
However, i don't feel comfortable automatically cleaning the source before saving it. I want to avoid save corruption or accidently saving it in a wrong format. So i didn't added that feature.
