### ISSUE TITLE
Bugs: Cannot open BasicPawn & Issues with configs

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#15]
Hi, 

When I try to open BasicPawn, sometimes the windows just appear in the taskbar but I cannot open the window. So I have to close it and delete the  windowinfo.ini file.
To workaround this I've made this batch file...

```
del windowinfo.ini
start BasicPawn.exe
```

Also even if I've set a configuration as main, it wouldn't be applied automatically to all the new files.

![basicpawnbug1](https://user-images.githubusercontent.com/21113203/35352457-45948238-0144-11e8-9db5-fbf9854d7116.gif) (Sorry for the typo)

**Comment by Timocop** [comment]
Sorry for the inactivity :/
Looks like the window is outside of the screen when the window is minimized. And if you close the window when its minimized it will save the bounds thats outside the screen. I made a commit that clamps the window bounds 776e56202cc3310c61a18f2ebe7c0803b5cc8dbd and a commit that ignores saving bounds when window is minimized b90b6ef73336433bc037982209cfd5c1da596c26. Should be fixed now.
(I like the Gifs btw.)

**Comment by Hexer10** [comment]
About the cfg issue?
