### ISSUE TITLE
A Bug + A Suggestion

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#17]
### There is a "commenting bug" that is caused by BasicPawn not recognizing the comment after a "compiler dictate" . 
(You are going to understand better in the gif <,<)
![commentbug](https://user-images.githubusercontent.com/21113203/36354823-2d5ee7ae-14da-11e8-86a3-fbf6a3fdba8d.gif)

### I'm wonder if it's possibile to add a feature that "auto indent" the bracket.
![automaticindent](https://user-images.githubusercontent.com/21113203/36354790-ea60aa5a-14d9-11e8-9f91-b49553e243d0.gif)

**Comment by Timocop** [comment]
Sorry for the delay, was quite busy.
Fixed the comment issue and added auto-close on brackets and strings too.
![](https://i.imgur.com/4GcKC0O.gif)
![](https://i.imgur.com/S2lxkPX.gif)
Theres only one issue with it. The define highlighting continues after the multi-comment, until the line ends.

**Comment by Timocop** [comment]
All done.
