### ISSUE TITLE
[Bug] [Linux] Can't save configs

### ISSUE THREAD

**Issue by Keplyx** [Timocop/BasicPawn#2]
I'm running Basic Pawn on Kubuntu 16.04, with Wine 2.6 (and .NET 4.5 installed)
I tried creating a custom config, with the manual setting, and only the include directory set:
![selection_003](https://cloud.githubusercontent.com/assets/23726131/25304675/46e03680-276c-11e7-928b-d19e73e81150.png)

But when I hit apply, it does not get saved 
![selection_004](https://cloud.githubusercontent.com/assets/23726131/25304687/8e4f3a34-276c-11e7-9753-24f9ed0c235b.png)
I found the config file, but it's empty...
![selection_005](https://cloud.githubusercontent.com/assets/23726131/25304694/bbd3079c-276c-11e7-97ce-2050f43a5736.png)

**Any way to fix this?**
I want to do this because I'm working inside a custom directory on my computer, with only custom includes, and I have a script for compiling. I can't use autocomplete (The only way I found was to have all the includes files in my custom directory) 

I just started using your software and it is very helpful (the only IDE for source pawn really working on linux). If I find some new bugs, I'll post them here!

**Comment by Timocop** [comment]
Did you hit "Save" at the very bottom? You need to hit "Save" when changing config settings.
![](http://i.imgur.com/R79MCEd.png)

**Comment by Keplyx** [comment]
Ooooohh, didn't see that little button...
I thought Apply was saving.

Thanks! So now it saves my config, but default is always selected on launch and I have to manually select my custom config. Am I missing something here?

**Comment by Timocop** [comment]
No, its by default. Gonna change it in the future too.

**Comment by Keplyx** [comment]
**Custom config starting by default with [v0.715](https://github.com/Timocop/BasicPawn/releases/tag/v0.715-beta):**

![spectacle tj4853](https://cloud.githubusercontent.com/assets/23726131/26398218/1c26850e-4079-11e7-8afb-71b3684a8352.png)

Nice fix thanks!
