### ISSUE TITLE
RegEx for Replace

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#23]
RegEx doesn't work (bug?) for Replace textfield. Tried to put $1 (with Regular Expressions Mode) but all search text replaces to **$1**.

Example:
> Search: **String\\:(.*)\\[\\]**
> Replace: **char\\[\\] $1**

Result:
replaced to **char\\[\\] $1**

**Comment by Timocop** [comment]
Its not buildin yet, didnt know thats a thing. Ill add it.
