### ISSUE TITLE
[Feature Ideas] Some features I think would improve Basic Pawn

### ISSUE THREAD

**Issue by Keplyx** [Timocop/BasicPawn#3]
I used Basic pawn a bit, and it's very useful! But I found it was lacking some features. Maybe some are already implemented, but I just couldn't find them (in that case, sorry...)

* **Let the user change syntax highlighting, add more themes**

This is good (from Eclipse):
![selection_007](https://cloud.githubusercontent.com/assets/23726131/25312080/2007a792-2810-11e7-9cde-334d5db6f8a4.png)

This has too much contrast:
![selection_006](https://cloud.githubusercontent.com/assets/23726131/25312078/10be6d20-2810-11e7-9f02-16ee183722f7.png)

* **Close opened tabs**

I don't want the starting file, and I opened a file twice, how can I close tabs?
![selection_008](https://cloud.githubusercontent.com/assets/23726131/25312094/9b7b1cf6-2810-11e7-9d70-63507ca306c0.png)

* **Open files from last instance on startup**

When working with multiple files, having to re-open all files can become annoying.

* **Code formating**

This is not very clear (current)
```
char sClassname[64];
GetEntityClassname(entity, sClassname, sizeof(sClassname));
if (StrContains(sClassname, "_projectile") != -1)
return Plugin_Stop;
```

This is better
```
char sClassname[64];
GetEntityClassname(entity, sClassname, sizeof(sClassname));
if (StrContains(sClassname, "_projectile") != -1)
          return Plugin_Stop;
```

**This is all the ideas I got for now, hopefully you like them. Keep on the good work!**

**Comment by Timocop** [comment]
Thanks for the feedback!
 > Let the user change syntax highlighting, add more themes

You can already change the TextEditor theme using the [**XML syntax file**](https://github.com/Timocop/BasicPawn/blob/master/BasicPawn/Resources/SourcePawn_Syntax.xml) and then import your custom XML syntax file in the settings. For now you can only choose between Normal and Inverted themes for the Windows Forms UI. Probably gonna be changed in the future.
![grafik](https://cloud.githubusercontent.com/assets/22834512/25313422/77f4b47c-282e-11e7-9c4f-b5e7cc666f56.png)

 > Close opened tabs

Like Notepad++ in the top right corner.
![grafik](https://cloud.githubusercontent.com/assets/22834512/25313456/7bd24680-282f-11e7-82ac-f0c95d773552.png)

 > Open files from last instance on startup

I was thinking about adding a StartPage with recent and pinned files like Visual Studios (and pretty much any other IDEs) StartPage.

**Comment by Keplyx** [comment]
> You can already change the TextEditor theme using the XML syntax file

I'm gonna try to make my own syntax file then.

> Like Notepad++ in the top right corner.

Well, this is what those buttons are for, I'm used to closing tabs with middle mouse, or having a cross on the tab.


Thanks for the quick answer!

**Comment by Keplyx** [comment]
Here, I made my own TextEditor theme based on Eclipse Dark theme:
![selection_009](https://cloud.githubusercontent.com/assets/23726131/25314763/502faa84-284a-11e7-9050-eb00a7fcbf18.png)
![selection_010](https://cloud.githubusercontent.com/assets/23726131/25314784/c262c014-284a-11e7-9f05-d9ae703297e9.png)
![selection_011](https://cloud.githubusercontent.com/assets/23726131/25314795/d238f8b4-284a-11e7-85f1-0c71621112d8.png)

[Here you can download it](https://pastebin.com/QbZaEd3N)

**Comment by Timocop** [comment]
Lookin good! Btw. you still can use the inverted color theme with your imported style. If you imported a custom TextEditor style it wont invert the color of the TextEditor just the other Windows Forms controls.
![grafik](https://cloud.githubusercontent.com/assets/22834512/25318515/9fd8f554-2890-11e7-9089-5a6f066ccea8.png)

Also, if you want to publish your custom theme maybe its a good idea to share it on AlliedModders in the BasicPawn thread? Or should i make a "custom styles" folder on master so people can use pull requests to add new styles?

**Comment by Keplyx** [comment]
Thanks! I think making a folder on master would be a good idea, so people downloading the software would be able to choose their own style (with a preview image).

**Comment by Timocop** [comment]
Done
