### ISSUE TITLE
Forwards autocompletion do not check for existing brackets

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#33]
Here's an example of how it looks like:
![bbac](https://user-images.githubusercontent.com/31375974/50387688-d3c22580-0713-11e9-974f-fa3168ce3a14.gif)
Basically if autocomplete forward function, it will append few additional brackets after it without checking if they are exists or not.

**Comment by Timocop** [comment]
Done. Should have done that sooner. Was annoying me too ;)
Preview:
![](https://i.imgur.com/Raru8iA.gif)
