### ISSUE TITLE
Unclosed bracket in defines breaks detection for enum structs and methodmaps 

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#34]
Here's how it looks like:
![6dl6buxdyw](https://user-images.githubusercontent.com/31375974/50387932-4d104700-0719-11e9-8b92-952768f02931.gif)
Was using F5 key to reload autocompletion, and the result was that unclosed bracket in defines breaks detection for enum structs and methodmaps. Also here's how my use case was looks like:
![image](https://user-images.githubusercontent.com/31375974/50387947-c445db00-0719-11e9-9844-da0e8b8dd1ec.png)

**Comment by Timocop** [comment]
Nice catch! Fixed.
