### ISSUE TITLE
"Enum structs" and "enum" color question

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#35]
Shouldn't they be blue color like methodmaps are? That question related more to VisualStudio2017_Dark style theme, don't know where else to ask that question since that style in that repo.

**Comment by Timocop** [comment]
Youre right, they should. Just wanted to ship this feature fast as possible before chistmas. Sometimes you forget little things and realized after you pushed the update lol. Will fix that.

**Comment by GAMMACASE** [comment]
Okay thanks, and also thanks that you keep updating basicpawn!
