### ISSUE TITLE
Does not properly highlight defines with escaped new line

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#37]
Here's an example of how it looks like:
![image](https://user-images.githubusercontent.com/31375974/50836762-10745a80-136b-11e9-8285-8644ef3ba826.png)

Basically you can escape new lines in defines using ``\`` symbol and write code on a new line, but basicpawn does not handle that type of things and does not fully highlight that define.

**Comment by Timocop** [comment]
Ive tried to do this before and i couldnt get it to work. The syntax format doesnt seem to have any 'escape-newline' option. The only end-stop for the highlighting is either via symbol or newline. Ive tried to set newline `\n` as a end-stop symbol but it ignores it.

I guess we are stuck with this mess unless i or someone else finds a solution. I want to avoid to solve this via code but if nothing works i may have to.

**Comment by GAMMACASE** [comment]
hmm but what if you do it vs like? here:
![image](https://user-images.githubusercontent.com/31375974/50846530-70293080-1380-11e9-8045-d93e90bd6916.png)
Or can this be an option to enable that style of defines and includes? That may also solve some troubles with trying to fully highlight define or any other related problem.

**Comment by Timocop** [comment]
Ahh the VS one looks pretty good, i think i may do that one instead. Just coloring``#define`` should do fine. The name is colored later after parsing.
