### ISSUE TITLE
Does not autocomplete on last line in editor

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#41]
Was confused for a first time on why it does not autocomplete any functions, later I noticed that it does not autocomplete only on last line, here's how it looks like:
![0x6xjrwha0](https://user-images.githubusercontent.com/31375974/51815330-35f0e600-22d1-11e9-8cc6-7f7e747fed1b.gif)

**Comment by Timocop** [comment]
Always those detailed gifs, i like 👍. Looking into it.
