### ISSUE TITLE
Unable to change config if default path is used

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#43]
I can't switch to another config if file that I'm working with is inside folder that is default for a different config. So here's an example: I have 2 configs A and B, A has default path set to ``D:\Folder\``, and I have a file under that folder, so when I open it it sets it's config to A as it should, but if I wanted to switch it to a config B, I can't, it simply returns back to A after configs tab closes.
So is it possible to add some sort of overriding for that feature? So I can switch configs for files if I wanted to but other files in that folder will still respect that folder and use proper configs.

**Comment by Timocop** [comment]
By default th default path is forced. But i can make it optional.

**Comment by GAMMACASE** [comment]
Yeah, that's would be cool. Cuz rn If I want to switch config for one particular plugin I need to move it out from the folder that is set default for a different config and then use config I want, which is pretty annoying.

**Comment by Timocop** [comment]
Now user specified (Known files) configs are highest priority. Should i force 'Default config paths' and 'Default config' when clicking "Find optimal config for this file" ? Which makes more sense.

**Comment by Timocop** [comment]
Done. However 'Find optimal configs...' will not update 'Known files'. You have to go into Settings and change them there to make it permanent.
