### ISSUE TITLE
Wrong color for defined word in preprocessor directives.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#46]
Here how it looks like rn:
SP:
![image](https://user-images.githubusercontent.com/31375974/52107540-d0219880-2607-11e9-8100-25a62df405c8.png)
VS:
![image](https://user-images.githubusercontent.com/31375974/52107550-d748a680-2607-11e9-98d4-cb7299fe68f4.png)
Looked into vs2017 dark theme .xml file, but didn't find anything where I can change it, but I think ``defined`` word here should be same color as ``#if``, ``#endif``, etc.

**Comment by Timocop** [comment]
Since we removed that preprocessor directives wont color the whole line anymore. We have to add all preprocessor directives words to a define section.

**Comment by GAMMACASE** [comment]
Alright, tried to look into sp compiler to find other possible words like ``defined`` but didn't find any others, except ``!defined``.

**Comment by Timocop** [comment]
There is a bunch. But those are not explictly used only in `#if`. You can use them anywhere those are operator after all. And normaly they should be colored blue (VS) same as `delete` and `view_as`.
https://github.com/Timocop/BasicPawn/blob/master/BasicPawn/Classes/FormMain/ClassAutocompleteUpdater.vb#L5095

**Comment by GAMMACASE** [comment]
Hm, but VS separates them, so delete and etc. are blue and defined is gray, I sent picture of how it looks like in vs.

**Comment by Timocop** [comment]
Even outside `#if`? Eg.
```SourcePawn
PrintToChat("Is Debugging: %d", defined DEBUG)
```

**Comment by GAMMACASE** [comment]
hmmm, not that much of an expert in c++, but seems like you can't do it like that in c++, was really surprised that you can do it like that in sp.
here:
![image](https://user-images.githubusercontent.com/31375974/52127315-d123eb80-2642-11e9-8339-80b0ede76c43.png)

but yeah I can see that defined word is inside reserved words (same where sizeof and new are in), https://github.com/alliedmodders/sourcepawn/blob/1.9-dev/compiler/sc.h#L422

**Comment by GAMMACASE** [comment]
Alright, now I'm really not sure if it should be changed, as you can use it outside of preprocess directives in sp.

**Comment by Timocop** [comment]
Maybe its better if we make them blue like all of the operators. We cant make it 100% VS anyways.
For example you can use `sizeof` and `tagof` in `#if` too:
```SourcePawn
int myArray[64];

#if sizeof(myArray)-1 == 64
	#error Invalid size
#endif

#if tagof myArray != tagof _:
	#error Tag should be 'int'
#endif
```

**Comment by GAMMACASE** [comment]
Not sure actually as I never saw your way of using defined anywhere else, but if it can't be as in VS, then let it be like now, also tagof and cellsof have same colors as defined, but same here dunno if it should be changed as they are rarely used (actually never saw them being used anywhere too). Things like sizeof() and new are matching VS dark theme rn, but again seems like sizeof() also does not work in preprocess directives in c++. So I actually don't know what color it should be, but seeing it as a blue would be kinda strange I guess (at least for me).

**Comment by Timocop** [comment]
I have made all variable/expression preprocessor operators related blue (`sizeof`, `typeof`, `tagof`, `delete`, `view_as` etc.) and define related gray (`defined`, `state` etc.). Should be a good balance. 2b40d5ec9be9245aff979c18ff6ad57e7a9fcb37

**Comment by GAMMACASE** [comment]
Hmm yeah, looks great, also while you at it, theres's ``cellsof`` operator, which was a thing back in the day, rn it returns same thing as ``sizeof()``, but I think it still can be added to OperatorKeywords section.

**Comment by Timocop** [comment]
Thanks :). Also added `exit` its still valid too.
