### ISSUE TITLE
Some weird behavior when autocompleting full function without brackets for methodmaps.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#47]
When trying to autocomplete methodmapped function that is already written but without any bracket after it, it will replace whole line with just that function, without prefixed variable, here's how it looks like:
![732jfsufw7](https://user-images.githubusercontent.com/31375974/52111558-17faec80-2615-11e9-91cc-38c887d23549.gif)

**Comment by Timocop** [comment]
Looks like some old code leftovers when BasicPawn wasnt much context aware with methodmaps and variables. This is actualy not a bug its intentional. But noone realy knew.
Back then its used to help with methodmap automcompletion:
![](https://i.imgur.com/8rbYwiM.gif)

**Comment by GAMMACASE** [comment]
Hm, is it possible to make it optional? Or maybe some sort of check what is before that function, some variable or methodmap name?

**Comment by Timocop** [comment]
Removed that feature. I dont think users even know about it anyways.
