### ISSUE TITLE
If you autocomplete function to fast, it may autocomplete wrong function

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#48]
So I was just typing function name, and instead of what I wanted I got absolutely different function. Here's how it looks like:
![qcyqpcfncj](https://user-images.githubusercontent.com/31375974/52113207-c1dc7800-2619-11e9-9b37-e094c8be03dc.gif)

As I can see that happens when you trying to autocomplete a bit to fast, before it find proper function, so it autocomplete function that was previously selected in autocomplete. I'm not sure if it's possible to fix, but would be nice if it's possible.

**Comment by Timocop** [comment]
I removed the autocompletion-update code from key presses. Because it was working in the UI thread which caused UI hanging and stuttering while writing. Its now in its own thread checking if the caret location has been changed every 500ms. I could make an option to control the syntax update thread refresh rate. Or just pump it up to 100ms.

**Comment by GAMMACASE** [comment]
Hm, yea option for it would be better then a hardcoded one

**Comment by Timocop** [comment]
Added option to change thread update rate in the settings. 100ms-2500ms range should be enough?

**Comment by GAMMACASE** [comment]
Yeah, don't think someone will go higher then 2500, also how does it affect performance if I set it to 100ms? Or is it insignificant?

**Comment by Timocop** [comment]
Doesnt affect the performance much. Most of the stuff is done in the thread. And all the other functions in the thread have hardcoded update rate. Like foldings, syntax update or highlight marker.

**Comment by GAMMACASE** [comment]
Alright then, should be good.
