### ISSUE TITLE
[BUG] Typo in search and replace field

### ISSUE THREAD

**Issue by Keplyx** [Timocop/BasicPawn#5]
Was searching for some words, when I found this:
![selection_019](https://cloud.githubusercontent.com/assets/23726131/25577652/20b764a8-2e68-11e7-8f5d-79df8dcd171e.png)

**Repalce** instead of Replace ;)

Also, would it be possible to add a renaming feature ([like here on eclipse](http://www.wikihow.com/Rename-Variables-in-Eclipse-(Java)))? Search and replace can be dangerous sometimes.

**Comment by Timocop** [comment]
Typo fixed. BasicPawn is not yet context aware, it doesnt know where variables are initalized and used. Its not realy needed _yet_. :)
