### ISSUE TITLE
Add possibility to select text in "Information" tab

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#50]
Right now you can't select text you want in Information tab, and sometimes when you want to copy error for example you need to open whole log in notepad and copy from there, which is annoying sometimes.
Is it possible to add way to select and then copy selected text in "Information" tab?
Or maybe another option here:
![image](https://user-images.githubusercontent.com/31375974/52534475-e25fad00-2d52-11e9-9a17-26866f3a1839.png)
that will let you copy only one line, instead of copy all.

**Comment by Timocop** [comment]
Added some more functionality to the information tab.
It will now show a small character at the end which indicates that you can do certain actions with it. Eg. Open in explorer or goto line. You can either double click on the entry or when selected right click to do other actions.
![](https://i.imgur.com/lGfpsBV.png)
Also added more entries in the context menu too.
![](https://i.imgur.com/JZBo1Fr.png)
Its still WIP. Tell me if you have more suggestions 😃

**Comment by GAMMACASE** [comment]
Is there a copy line option or smth close to that? But otherwise looks good to me.

**Comment by Timocop** [comment]
Yes there is. Just like "Open in Notepad". You can select more lines too now.
![](https://i.imgur.com/xbvs55J.gif)

**Comment by GAMMACASE** [comment]
Alright, that's nice. Also just thought, what about some short cuts? Like selecting lines I wanted, and pressing ctrl+c to copy all selected lines without any need to go though 2 sub menus.

**Comment by Timocop** [comment]
Thats a good idea!

**Comment by Timocop** [comment]
Done. Ctrl+C to copy minimal (without timestamp). Shift+Ctrl+C for full.
