### ISSUE TITLE
Does not redirect to error when it's originated from included .sp or .inc file

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#51]
If error is in included .sp or .inc file and if you will try to navigate to it through "Information" tab, it will not do anything, like here, I created few errors, but I'm unable to navigate to them through "Information" tab:
![image](https://user-images.githubusercontent.com/31375974/52534612-daa10800-2d54-11e9-9681-3b739f14cc88.png)

**Comment by Timocop** [comment]
Because they are relative paths, only absolute paths are clickable.
Currently it compares all open tab- and include files with the absolute path in the compiler output.
Ill make the information tab more flexible soon 👍

**Comment by GAMMACASE** [comment]
Alright, cool!
