### ISSUE TITLE
Autocomplete preview suggestion

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#52]
Would be good if autocomplete window could print code preview for any non-native methods/functions or properties (It could be toggleable from settings).
![default](https://user-images.githubusercontent.com/11666918/52910537-982e7c80-32ba-11e9-88e1-0fcacbd7705b.png)

**Comment by Timocop** [comment]
Sounds good, However there needs to be a limit how many lines of the code should be displayed. It could be an issue displaying large method/properties. Ill add an option for that in the settings too.

**Comment by GAMMACASE** [comment]
What about some sort of scroll ability? Like it will display you 10 lines and then you can scroll up and down if you want to see more? Or smth like in VS, where you can right click on variable/method etc. and click Pick definition, and it will show you it like that: 
![image](https://user-images.githubusercontent.com/31375974/52915631-9cbd5a00-32e7-11e9-93c0-387644c16f7c.png)
and you can scroll there, edit, etc. It's like 2nd text tab on top of current tab. Not sure if is that possible rn, but if it is that also would be cool!

**Comment by Timocop** [comment]
I was thinking about something like 'Code Peek' too. But BP is still not yet context aware. But im planing extending the autocompletion tab with more features anyways. Just like the information tab.

**Comment by Timocop** [comment]
Sorry for the long wait. Recently i have added a 'Peek definition' feature to quickly lookup definitions of methods, functions, properties etc. (#67, #64)
![2020-02-13_13-38-49](https://user-images.githubusercontent.com/22834512/74436371-9dd78780-4e66-11ea-952d-3a29c2fa829a.gif)

**Comment by Timocop** [comment]
@MAGNAT2645 Since i've added 'Peek definition' in the autocomplete window (like in the gif in my answer above), is this something you consider as solved?

**Comment by MAGNAT2645** [comment]
Yes i guess.
