### ISSUE TITLE
Freeze problem

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#53]
Idk why but if you paste a lot of (11000+ in my case) lines of code, BasicPawn just freezes and not response for a few seconds. Scrolling large code also causes some lags.

**Comment by Timocop** [comment]
Thats alot of code. You should split it up into includes. For readability sake too.

BasicPawn and the editor drawings happens over CPU since its build with WinForms unlike WPF which happens over GPU. Which makes it more compatible but slower.

Is the code publicly available so i can test around?

**Comment by Timocop** [comment]
Ive tested around a little copy & paste alot of lines. Seems like the issue is caused by the orange/green line-changed marks on the left bar. Too much items to draw. A workaround would be to safe and reopen the file so all marks are gone.

**Comment by MAGNAT2645** [comment]
In my case, it was [Unofficial Freak Fortress](https://github.com/Batfoxkid/FreakFortressBat).

So, i can close this since I got a solution to problem.
Also would be good to add option or hotkey that will clear all marks.

**Comment by Timocop** [comment]
Already on it 👍 
Ill reopen this untill i finished the commit.

**Comment by Timocop** [comment]
Done 59f9981ac13b3d9c4884e66aa107369089ac6453. You can now disable the whole icon sidebar or disable line state colors if you dont need them. A histoy limit of 1000 should be good enough. Ive tested it with the testcase above. You can go lower if you still have lag on big files.
![](https://i.imgur.com/YEUeumE.png)
