### ISSUE TITLE
"Details" menuItem doesn't get re-checked after pressing "Build" or "Reindent" or other events which toggle it.

### ISSUE THREAD

**Issue by Nickelony** [Timocop/BasicPawn#55]
![L7EH45ZeYN](https://user-images.githubusercontent.com/20436882/54424002-3ffc6600-4712-11e9-964f-fe28ed322a0c.gif)
It's really annoying because I don't want to see it all the time and if I press "Build" I have to click on the menuItem twice to toggle it off.

**Comment by Timocop** [comment]
Nice catch. Fixed.
