### ISSUE TITLE
SaveFileDialog issue.

### ISSUE THREAD

**Issue by Nickelony** [Timocop/BasicPawn#56]
in `BasicPawn/Controls and Forms/Main/Classes/ClassTabControl.vb`
`i.FileName = m_Tab(iIndex).m_File` returns the full file path instead of just the name.
![image](https://user-images.githubusercontent.com/20436882/54456231-f0438c00-475d-11e9-9950-7602505f67eb.png)

**Comment by Timocop** [comment]
The `FileName` property can handle both filename and path. I just choosed to use the path because it requires less lines. I can change it however.
