### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by Nickelony** [Timocop/BasicPawn#57]
If there is no `compiled` directory, the compiler throws an error. It would be nice if instead of throwing this error, BasicPawn would just create the missing directory.

**Comment by Timocop** [comment]
You mean in `Automatic` detection mode?

**Comment by Nickelony** [comment]
No, I mean this issue:
![0lFCvvEkJn](https://user-images.githubusercontent.com/20436882/54478278-a36cbd80-4810-11e9-81c4-7946daceb464.gif)
Pseudocode:
`if(!Directory.Exists(compileOutputFolder))
    Directory.Create(compileOutputFolder);`

**Comment by Timocop** [comment]
Sorry i should have expressed myself more. I assume you are using `Automatic` detection method in the config to detect compiler path etc.?
![](https://i.imgur.com/C534axm.png)

**Comment by Nickelony** [comment]
Oh yes, I misunderstood you. Yup, that's the case.
