### ISSUE TITLE
Autocomplete is not working?

### ISSUE THREAD

**Issue by Aldabeth** [Timocop/BasicPawn#58]
Hi! Autocomplete wont work for me, it is showing everything fine (autocomplete tab), but it wont complete it for me, I need to write it myself for some reason.

**Comment by Aldabeth** [comment]
Here is an example.
![example](https://user-images.githubusercontent.com/46329028/55752458-5fa05900-5a48-11e9-9862-db4a4aeff6ab.gif)

**Comment by Timocop** [comment]
It should autocomplete fine if you press Ctrl+Enter. All available shortcuts are listed in "Help > Special Controls"

**Comment by Aldabeth** [comment]
Thank you very much!

**Comment by Timocop** [comment]
I assume this is solved? Reopen this if you have problems with the autocomplete function again. :)
