### ISSUE TITLE
Add alt and arrow keys moving a line up or down

### ISSUE THREAD

**Issue by GameChaos** [Timocop/BasicPawn#59]
Holding alt and pressing up or down arrow keys should move the current line up or down, like in vscode. Would be a really neat feature.
![U6Be7oP3Uy](https://user-images.githubusercontent.com/25118806/57384820-e5373600-71b9-11e9-98aa-386cbb664fba.gif)

**Comment by Timocop** [comment]
Done. However, `Alt` alone is already used in WinForms like in Menus by default. That may cause some shortcut conflicts. So i had to change the shortcut into `Shift+Ctrl+Up/Down` instead.

![](https://i.imgur.com/XePfC50.gif)
