### ISSUE TITLE
Naming variable with include name results in missing autocompletion

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#60]
So I've recently downloaded [json library for sm](https://github.com/clugg/sm-json) and after including it and giving my variable name `json` it missed autocompletion for it entirely, renaming it fixes that issue, but I'm not sure what is the cause for that behavior.

Here's a bit _long_ gif:
![aw9Hc4f0G4](https://user-images.githubusercontent.com/31375974/57451051-cba0f780-7268-11e9-9e16-b8ae62ea5176.gif)

Also in the gif above I pressed f5 each time I renamed my variable and waited for it to fully load, so it's not the case.

**Comment by Timocop** [comment]
The variable autocomplete will try to filter out duplicate names. It will also check any preprocessor directives such as `#include` file names. So if you use `#include <my_lib>` then create a variable like `my_lib` the autocomplete wont show it. I changed this behaviour.
