### ISSUE TITLE
Open basicpawn main window even if search & replace window opened too

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#63]
So basically if you have "Search & Replace" window opened and then you switch to some other program/window (loose the focus of basicpawn) and want to return to basicpawn it results in that thing:
![image](https://user-images.githubusercontent.com/31375974/59546503-2cda7b80-8f37-11e9-8c33-ce1ad898ff56.png)
It asks you what window you want to open, and that is pretty annoying. Yes I can close "Search & Replace" window and thing will not annoy me anymore, but then again later I can use that for something and forget to close it, as it always happens.
I'm not sure if it's something you can fix or do anything with it, but notepad++ in the same situation opens main window even if "Search" window opened and do not ask me exactly what window to open.

**Comment by Timocop** [comment]
I see what you mean. Im actualy not using windows 'compact' taskbar so i didnt realize it was an annoying issue. Ill fix that.

**Comment by Timocop** [comment]
Ive removed it from the taskbar. Should been fixed now.
