### ISSUE TITLE
Go To Definition option

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#64]
Sorta same as issue #52, but still a bit different, would be cool to have an option ``Go To Definition`` like in VS, that redirects you to function, variable, methodmap, etc. definition. Rn that is possible via ``List References`` option and then manually find where it is defined.

**Comment by Timocop** [comment]
Already in the workings 👍 
![](https://i.imgur.com/WquEc9o.gif)

**Comment by GAMMACASE** [comment]
Oh that's nice!

**Comment by Timocop** [comment]
Done. Should be available in the next release.
