### ISSUE TITLE
Go to declaration Feature

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#67]
It think it would be a nice addition to have a features similar to what other IDEs (like Intellij IDEA) have, which is that with a CTRL + LEFT CLICK, you can find where a variable or function was defined.
![ReferenceExample](https://user-images.githubusercontent.com/21113203/71917961-9941f400-3181-11ea-9ace-c6d14813a3ce.gif).
This also work in the opposite way where you can find where a variable or function is used and go back to its usage (I think this would be harder to implement).
![ExampleUsage](https://user-images.githubusercontent.com/21113203/71918020-b5459580-3181-11ea-8c75-ba2a4a50fc46.gif)

**Comment by Timocop** [comment]
I assume you mean adding a shortcut? Since the 'Find definition' and 'Find references' already exist.

**Comment by Hexer10** [comment]
Oh I didn't know about that, thanks for letting me now.
Yes then, maybe a way to set a custom shortcut would be awesome (since I can already see that there are CTRL + L and CTRL + SHIFT + L as default shortcuts)

**Comment by Timocop** [comment]
Sorry for the long delay, ive been busy :|

Ive added the CTRL + CLICK shortcut in the recent commits:
![2020-02-07_17-19-50](https://user-images.githubusercontent.com/22834512/74046533-02aa6200-49cf-11ea-9194-9c1e31796d77.gif)
