### ISSUE TITLE
Send command ONLY after BUILD

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#68]
Right now the code in the `Post-build event command line` gets execute every time I compile the code whether I build or test code.
Is there any way to execute it only after I build the code? 
For example I added a this command line
```
D:\Tools\Putty\pscp.exe -pw psw "%bp_conf_output%\%bp_source_filename%.smx" "user@server:/foo/sourcemod/plugins/%bp_source_filename%.smx"
```
to automatically upload my code via scp but it gets uploaded even when I test my code which is annoying.

(Indeed if I only test the code without compiling even once the code just fails)

**Comment by Timocop** [comment]
Yes, you can use `%bp_testing%`  whenever to check if you compile or test.

Example:
```batch
if "%bp_testing%"=="false" (
copy /y "%bp_conf_output%\%bp_source_filename%.smx"  "%bp_startdir%\RELEASE\"
echo Binary copied to RELEASE directory!
)
```

Also since you mentioned FTP have you tried BasicPawns SFTP/FTP plugin?
It adds a upload feature in the compile menu.
[Offical Plugins](https://github.com/Timocop/BasicPawn/tree/master/Plugin%20Releases)

**Comment by Hexer10** [comment]
I haven't tried, because I thought that it only supported FTP, however I will try now.

**Comment by Hexer10** [comment]
I tried the extension and indeed it supports SFTP, tough I always have to go thru the menu to upload a file and manually type the path, whereas with a custom command line I can build and upload automatically which is more reliable imo.
