### ISSUE TITLE
False errors when trying to read include files.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#69]
I have a config that uses 2 include paths, and only one of them contains ``include/glib/memutils.inc`` file, and everything works and compiles fine, but I get that error (pic below) every time I compile, not that it affects anything, just found it reasonable to report it.

![image](https://user-images.githubusercontent.com/31375974/72116410-3b690400-335b-11ea-84a4-358cd282fb90.png)

**Comment by Timocop** [comment]
Are you using ``#tryinclude`` for this include file? This can happen with ``#tryinclude``.

**Comment by GAMMACASE** [comment]
nope, normal ``#include`` also I want to tell that I use multiple ``.sp`` files included after that ``memutils.inc`` that also use (but not ``#include`` it directly) that ``memutils.inc``

**Comment by GAMMACASE** [comment]
Here's source code that I used: https://github.com/GAMMACASE/MomSurfFix

**Comment by Timocop** [comment]
I removed that message. Was quite spammy anyways and the compiler already tells you whenever a file is missing. Which is way better in my opinion. You can get the newest dev build to remove that message. 👌
