### ISSUE TITLE
Jump to new line

### ISSUE THREAD

**Issue by Alienmario** [Timocop/BasicPawn#71]
Add an action for shift + enter to add new line and position at the start of it (including previous line indentation).
This is useful when you're in the middle of a line, so you don't have to reposition the caret to the end of it manually and then press enter.

This is the default for jetbrains editors https://www.jetbrains.com/help/rider/Adding_Deleting_and_Moving_Lines.html

I've also just noticed that sublime text uses ctrl + enter for this, so ideally shortcuts would be configurable.

**Comment by Timocop** [comment]
``Ctrl + Enter`` and ``Shift + Ctrl + Enter`` are already used for autocompletion and i have no plans of changing it right now. However, it does look like Notepad++ also has this feature but just uses different shortcuts ``Ctrl + Alt + Enter`` and ``Shift + Ctrl + Alt + Enter`` which are unused in BasicPawn. I'll probably implement those instead.
