### ISSUE TITLE
Compiler can not be found ! What could be a problem ?

### ISSUE THREAD

**Issue by ruinedmoon** [Timocop/BasicPawn#72]
User created a new source file
User opened a new file: ...\BasicPawn\plugins\retakes\retakes_standardallocator.sp
Compiling source started!
Compiling failed! Compiler can not be found!

When i try to compile this plugin, i got this error...

**Comment by Timocop** [comment]
Do you still need help with this problem?

Either way, you have two options:
 1. (**Automatic**) Place your source file into the SourceMod scripting directory and open it from there. BasicPawn will automatically search the compiler and its includes relative to the opened source file.

2. (**Manual**) For this you have to create a new config in the settings and enter compiler, include and output path, so BasicPawn always knows where all the tools are located. Which means you can also work outside of the SourceMod scripting directory. You can find the config in '_Tools > Settings & Configs > Configs_'.
