### ISSUE TITLE
Add symbols representing tabs and spaces.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#74]
This was a feature before, now it's gone, would be cool to see that as an available option again.
Example pic:
![image](https://user-images.githubusercontent.com/31375974/80353513-24084500-887e-11ea-9739-5a63b7fb57df.png)

**Comment by Timocop** [comment]
I've made them optional. Keep in mind the whole reason why i removed them is because their performance impact when a lot of tabs are present in the view. 14eb63f949d6a764b3af263e5053e8e32835cd75
