### ISSUE TITLE
Single instance in Search & Replace window doesn't work

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#75]
Here's an example on newly created file with one line:
![image](https://user-images.githubusercontent.com/31375974/82538294-352e3400-9b54-11ea-9f2f-411cc6ccf970.png)
As can be seen from screenshot, ``Single instance`` is ticked (And it was ticked before ``List All`` button was pressed), and it still shows same line twice cuz there's two matches on that line.

**Comment by Timocop** [comment]
"Single instance" means only one instance of the Search & Replace window. 😄 I wasn't sure where to put the checkbox because its quite crowded already. Maybe i'll move it somewhere else.

**Comment by GAMMACASE** [comment]
Ahhh well having that feature to filter output from duplicate lines would be great.

**Comment by Timocop** [comment]
That's doable. But the only downside is that the whole line will be selected instead, since you loose the ability to select individual results.

**Comment by GAMMACASE** [comment]
Yea I guess this is alright.

**Comment by Timocop** [comment]
Fixed.
