### ISSUE TITLE
Autosave Feature

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#77]
I know that BasicPawn is kind of based on Visual Studio Code.
But i don't see an autosave option. It hasn't been implemented yet?
This feature might be useful because it is implemented even in NotePad++.

**Comment by MAGNAT2645** [comment]
Oh, NotePad++ has autobackup feature (default every 7 sec. as i see) but i meant autosave in general so you don't need to press Ctrl+S to save your changes.

**Comment by Timocop** [comment]
Done. 0980c4838831cc8d79bf328d738f221a496053eb
