### ISSUE TITLE
 BasicPawn in Linux(Wine) not displayed correctly

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#81]
When started BasicPawn displays this:
![image](https://user-images.githubusercontent.com/21113203/101184765-61715400-3651-11eb-8af2-bd9ac8515f0b.png)
The program then becomes unresponsive and I'm unable to close is if not forcefully.

This is the wine output:
```
wine BasicPawn
0079:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0079:fixme:uiautomation:UiaClientsAreListening ()
0079:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x32e0c8, 0x3afdcb0, 0x32e0cc, 0x32e0c0
0079:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x32e0c8, 0x3afdcb0, 0x32e0cc, 0x32e0c0
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x3abea74,0x3ae7a00): stub
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:gdiplus:GdipGetLineSpacing ignoring style
0079:fixme:richedit:ME_HandleMessage EM_GETLANGOPTIONS: stub
0079:fixme:richedit:ME_HandleMessage EM_GETLANGOPTIONS: stub
0079:fixme:richedit:ME_HandleMessage EM_SETLANGOPTIONS: stub
```
I'm on `Ubuntu 20.10`.

**Comment by Timocop** [comment]
Mmh looks like a Wine problem. 
 * What Wine version are you using?
 * Are you using x86 or x64 to run BasicPawn for Wine?
 * What .NET Framework did you install?

**Comment by Hexer10** [comment]
I tried both with `wine` and `wine64`, the wine version is `5.0.3` and I've instealld the .NET Framework 3.5 from this link https://appdb.winehq.org/objectManager.php?sClass=version&iId=10166

**Comment by Timocop** [comment]
Just installed Ubuntu 20.10 inside VirtualBox. Used PlayOnLinux to run BasicPawn, seems to run just fine.
![image](https://user-images.githubusercontent.com/22834512/101201288-cdf74d80-3667-11eb-9f38-6fa4d5a62c90.png)
Make sure Mono is not installed.

**Comment by Timocop** [comment]
PlayOnLinux installs additional Microsoft fonts, maybe that could be the issue.

**Comment by Hexer10** [comment]
I had mono installed at that caused the issue,I created a 32bit wine prefix and uninstalled mono
