### ISSUE TITLE
Low font quality with Ultra-Wide monitor

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#82]
I've been using BasicPawn on my laptop and so far it was all fine but now that I've switched to my pc(windows 10) which as a ultra wide monitor (3400 x 1400) the font quality of the application seems a bit poor, I've attached a screenshot so you can get a better idea:
![image](https://user-images.githubusercontent.com/21113203/101954591-a4589c00-3bfc-11eb-8c44-c9bf4f83ffae.png)
I'm not sure if you can perceive from the screenshot but here it looks a lot worse in BasicPawn rather than in IDEA. (I've tried using the same font in both IDEs but it didn't help)

**Comment by Timocop** [comment]
Thats because BasicPawn isnt DPI aware yet. It will scale the whole app by your Windows DPI settings, making things blurry it the process. I recently got a 2K monitor so i can finally test stuff and make it DPI aware. This probably takes some time however because im busy at the moment. Of course, you *could* override the DPI settings for the app, but some fonts and controls might glitch or look deformed.

**Comment by Hexer10** [comment]
Thanks for the reply! Scaling the application DPI from the windows properties definitely worked, the startpage looks deformed but the editor is displayed nicely
![image](https://user-images.githubusercontent.com/21113203/102009664-48476200-3d39-11eb-996e-bfe687194807.png)

**Comment by Timocop** [comment]
I'm currently working to make BasicPawn DPI aware. Seems pretty good so far:

![image](https://user-images.githubusercontent.com/22834512/102645772-49c2c100-4163-11eb-8889-00b51d578225.png)
![image](https://user-images.githubusercontent.com/22834512/102645923-855d8b00-4163-11eb-8c82-ed3f37a87837.png)

You can try it out in the dev build (plugins not published yet):
https://ci.appveyor.com/project/Timocop/basicpawn/builds/36911753/artifacts

**Comment by Timocop** [comment]
If you are testing the dev build, please report bug and glitches if you found any, thank you.

**Comment by Hexer10** [comment]
I'll make sure to try the dev version out

**Comment by Timocop** [comment]
Official update published. Re-open if there are any issues.
