### ISSUE TITLE
Search window doesn't remember some options

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#83]
Hi,

That's will be good to remember:

1) Entered text in "Search fileld", so next time when you open this window you don't have to re-enter in again.
Also, good to have it always be selected once you opened "Search" window, so you can instantly replace it by entering new phase without need to erase it firstly.

2) "List all type" frame.
So, would be cool, these options be applicable not only for "List all" button, but also for a default search (to be able to fast search / jump to results in all opened tabs).

**Comment by Timocop** [comment]
Done. 60b5722947e3b8b026bce6d31eb2013d3da28f21
