### ISSUE TITLE
ClassFoldings Crash

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#85]
```
System.NullReferenceException: В экземпляре объекта не задана ссылка на объект.
   в BasicPawn.ClassTabControl.ClassTab.ClassFoldings.UpdateFoldings()
```

Translation: Object reference not set to an instance of an object.

I can't tell you exactly what to do to reproduce it, sorry.
I just inserted new forward, deleted some arguments and, looks like clicked somewhere in { of empty function body.
```
public Action OnPlayerRunCmd(int client, int &buttons, int &impulse, float vel[3], float angles[3], int &weapon)
{
}
```

Application didn't completely crash. I was able to click "Continue" and BasicPawn was able to continue the normal work without any lost. And that's great!

**Comment by Timocop** [comment]
Did this ever happen again? Can this be closed?

**Comment by dragokas** [comment]
Sorry, not sure. I didn't use it a lot for the last time.
I'll let you know if a similar happens.
Thanks for the update!
