### ISSUE TITLE
[Improvement] Keep Tab order

### ISSUE THREAD

**Issue by Keplyx** [Timocop/BasicPawn#9]
The start page is very useful and helps save time, however, when I open back my files, the tab order seems random.
![spectacle m14680](https://user-images.githubusercontent.com/23726131/27469927-ed4adf88-57f1-11e7-90b1-5c37179fc225.png)

Would it be possible to open back files in the same order they were closed? So if I have the main file in first, then the secondaries in a certain oder, would it be possible to keep that order when I open them back with the start page?
![spectacle m14095](https://user-images.githubusercontent.com/23726131/27469887-c6bba69a-57f1-11e7-8a18-7acf5d87626f.png)

That's not a big deal, but I like to have my project organized

**Comment by Timocop** [comment]
The tab sorting depends on the file modified date. If you save a file it will be the most recent. A workaround for that would be to "Save all" (File > Save all) files to keep the tab order.
(You can get the 139ed8a60cc8e4bde350bde26ecbb1e720535dce commit which fixes the 'Save all' reversed saving issue.)

Good news is im currently working on a project system which makes your life even more easier :P

**Comment by Timocop** [comment]
Implemented simple projects db474378772c6f8cb33ad9bc048af984feaad914. Let me know if there are any issues! Closing this.

**Comment by Keplyx** [comment]
Thanks! A project system would be really awesome! But I don't know how to get a commit. (I'm still a beginner with github)

**Comment by Timocop** [comment]
Click the green checkmark next to the commit name (Means successfully build) and go to artifacts. There you can find the build. [Or click here for latest builds.](https://ci.appveyor.com/project/Timocop/basicpawn/build/artifacts)
