### ISSUE TITLE
Translation editor doesn't support special characters

### ISSUE THREAD

**Issue by Adrianilloo** [Timocop/BasicPawn#91]
When setting a phrase which contains for example single quotes (`'`) , an escape symbol is automatically prepended when saving it and then upon exporting the file, it gets printed literally in game. Ideally, no escaping should need to happen, in order to fix the issue.

This rather forced me to keep using normal translation editing via BasicPawn tab since I prefer not to expand English contractions instead (e.g. `don't` -> `do not`)

**Comment by Timocop** [comment]
Sorry for the long delay. This is fixed now. Please wait for the new plugin release.

**Comment by Timocop** [comment]
Please update to BasicPawn v0.851 and download the new plugin version.
