### ISSUE TITLE
[Feature Request] Ability to "Replace All" in all opened tabs simultaneously

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#98]
At the moment Ctrl + F option "All opened tabs" is only applicable for "List all" function.

It would be cool to have the ability to apply it for "Raplace All" function.

Related to: https://github.com/Timocop/BasicPawn/issues/83

Thank you!

**Comment by Timocop** [comment]
Done. 3150ddfd35ba9d745ec6bf627847c6ce572ed1fd
